### PR TITLE
Version 2.0.0

### PR DESCRIPTION
**Pull request by mimischi**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mimischi** [comment]
@conda-forge-admin, please rerender

**Comment by kain88-de** [comment]
@mimischi was this branch uploaded to this repo or from a fork?

**Comment by mimischi** [comment]
I pushed it directly to this repository. Should one always do it from a fork for conda?

**Comment by kain88-de** [comment]
Any push to *this* repository triggers the CI builds including publishing a
repo. This is why the PR template makes you check you used a fork.

**Comment by mimischi** [comment]
I see. Was wondering what that was about. Will make sure to do it
differently next time :)

Am Di., 30. Okt. 2018, 21:55 hat Max Linke <notifications@github.com>
geschrieben:

**Pull request merged**
